### ISSUE TITLE
Could the open code sove flow stability of the flow past a 3-D bluff body? 

### ISSUE THREAD

**Issue by hongfu2233** [nekStab/nekStab#48]
Could the open code sove the flow stability of a flow past a 3-D bluff body?

**Comment by loiseaujc** [comment]
Hej,

Sorry for the late reply. As long as you can run the flow configuration with the legacy Nek5000 code, you should be able to use nekStab to compute both the base flow and study its linear stability. Which particular case do you have in mind ?

**Comment by hongfu2233** [comment]
Hi, Thank you for your reply. I want to conduct the linear stability analysis on  flow past a wall-mounted cube. Would you kindly provide some case examples? Thank you. Best,Hongfu---- Replied Message ----
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/19/2023 20:06
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [nekStab/nekStab] Could the open code sove flow stability of the flow past a 3-D bluff body? (Issue #48)
        
      
    
  

Hej,
Sorry for the late reply. As long as you can run the flow configuration with the legacy Nek5000 code, you should be able to use nekStab to compute both the base flow and study its linear stability. Which particular case do you have in mind ?

**Comment by hongfu2233** [comment]
Hi, Thank you for your reply. I want to conduct the linear stability analysis on  flow past a wall-mounted cube. Would you kindly provide some case examples? Thank you. Best,Hongfu---- Replied Message ----
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/19/2023 20:06
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [nekStab/nekStab] Could the open code sove flow stability of the flow past a 3-D bluff body? (Issue #48)
        
      
    
  

Hej,
Sorry for the late reply. As long as you can run the flow configuration with the legacy Nek5000 code, you should be able to use nekStab to compute both the base flow and study its linear stability. Which particular case do you have in mind ?

**Comment by loiseaujc** [comment]
To set up the case (i.e. mesh, boundary conditions, flow parameters, etc.), I strongly suggest taking a look at the [Nek5000](https://github.com/Nek5000/Nek5000) repo. Once you can run a simple simulation with Nek5000, extending Nek's capabilities with those implemented in nekStab is pretty simple. You can look at our [examples](https://github.com/nekStab/nekStab/tree/main/examples) folder for more details.
